### ISSUE TITLE
Beamsplitter cube rotated

### ISSUE THREAD

**Issue by polwel** [cbersch/pst-optexp#4]
The beamsplitter cube is rotated by 45 degrees.
![image](https://user-images.githubusercontent.com/7679808/131361733-08526c1b-009f-4ebd-aa07-488d1872e45f.png)

It should look like this (section 4.20 from the manual):
![image](https://user-images.githubusercontent.com/7679808/131362244-8c9dee93-ea32-40f3-bd22-5d3afd0f7d3a.png)

Source:
```latex
\documentclass{article}
\usepackage{pstricks}
\usepackage{pst-optexp}
\begin{document}
\begin{pspicture}(3,2)
    \beamsplitter[beam,bsstyle=cube,](0,1)(2,1)(2,0){BS}
\end{pspicture}
\end{document}
```

Built on a fairly recent miktex install. In particular, I have v6 of `pst-optext`.

Log file: [pst-optexp.log](https://github.com/cbersch/pst-optexp/files/7077666/pst-optexp.log)

**Comment by cbersch** [comment]
Unfortunately, pst-optexp doesn't work with XeTeX.

**Comment by polwel** [comment]
Unfortunate.
